---
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #checkout source code to working directory
      - run:
          name: installing packer
          command: |
            pwd
            wget https://releases.hashicorp.com/packer/1.5.3/packer_1.5.3_linux_amd64.zip
            ls
            unzip packer_1.5.3_linux_amd64.zip
            sudo mv packer /usr/local/bin

workflows:
  version: 2
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master