---
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout #checkout source code to working directory
      - run:
          name: installing packer
          command: |
            pwd
            wget https://releases.hashicorp.com/packer/1.5.3/packer_1.5.3_linux_amd64.zip
            ls
            unzip packer_1.5.3_linux_amd64.zip
            sudo mv packer /usr/local/bin
            packer validate -var 'source_ami='${source_ami} template.json
            packer build \
            -var 'aws_access_key='${aws_access_key} \
            -var 'aws_secret_key='${aws_secret_key} \
            -var 'source_ami='${source_ami} \
            -var 'aws_region='${aws_region} \
            -var 'ami_users='${ami_users} \
            template.json

workflows:
  version: 2
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                -master